# Generated by Django 3.0.14 on 2022-01-17 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='pie_chart',
            new_name='daily_path',
        ),
    ]
