# Generated by Django 3.0.14 on 2022-01-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='homelike_latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='appuser',
            name='homelike_longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='appuser',
            name='workingplacelike_latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='appuser',
            name='workingplacelike_longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
