# Generated by Django 3.0.14 on 2022-01-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailypathapp', '0004_auto_20220118_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpslog',
            name='id',
            field=models.BigAutoField(db_column='GPSLog_id', primary_key=True, serialize=False),
        ),
    ]
