# Generated by Django 3.0.14 on 2022-01-14 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dailypathapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.BigAutoField(db_column='interval_id', primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('category', models.CharField(max_length=70)),
                ('location', models.CharField(max_length=70)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('pie_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='dailypathapp.DailyPath')),
            ],
            options={
                'db_table': 'interval',
            },
        ),
    ]
