# Generated by Django 3.0.14 on 2022-01-06 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piechartapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.BigAutoField(db_column='interval_id', primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('interval_created', models.DateTimeField(auto_now_add=True)),
                ('interval_updated', models.DateTimeField(auto_now=True)),
                ('pie_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='piechartapp.PieChart')),
            ],
            options={
                'db_table': 'interval',
            },
        ),
    ]
