# Generated by Django 3.0.14 on 2022-01-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intervalapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interval',
            old_name='interval_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='interval',
            old_name='interval_updated',
            new_name='last_updated',
        ),
    ]
