# Generated by Django 3.0.14 on 2022-02-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervalapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervalstay',
            name='emotion',
        ),
        migrations.AddField(
            model_name='intervalstay',
            name='location_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
