# Generated by Django 3.0.14 on 2022-02-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervalapp', '0002_auto_20220221_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalstay',
            name='location_id',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
