# Generated by Django 3.0.14 on 2022-01-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervalapp', '0002_auto_20220118_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='interval',
            name='percent',
            field=models.FloatField(default=0.0),
        ),
    ]
