# Generated by Django 3.0.14 on 2022-02-20 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='app_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fcmToken', models.CharField(blank=True, default='abc', max_length=100, null=True)),
            ],
            options={
                'db_table': 'app_user',
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(db_column='coordinates_id', primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=70)),
                ('location', models.CharField(max_length=70)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Estimate', to='accountapp.AppUser')),
            ],
            options={
                'db_table': 'estimate',
            },
        ),
    ]
