# Generated by Django 3.0.14 on 2022-01-14 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='app_user', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_user',
            },
        ),
    ]
