# Generated by Django 3.0.14 on 2022-02-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='fcmToken',
            field=models.CharField(blank=True, default='abc', max_length=200, null=True),
        ),
    ]
