# Generated by Django 3.0.14 on 2022-02-01 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_auto_20220126_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='homelike_latitude',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='homelike_longitude',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='workingplacelike_latitude',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='workingplacelike_longitude',
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(db_column='coordinates_id', primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=70)),
                ('location', models.CharField(max_length=70)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Estimate', to='accountapp.AppUser')),
            ],
            options={
                'db_table': 'estimate',
            },
        ),
    ]
