# Generated by Django 3.0.14 on 2022-02-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='FCM_token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
