# Generated by Django 3.0.14 on 2022-02-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0003_appuser_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='FCM_token',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
