# Generated by Django 3.0.14 on 2022-02-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0005_auto_20220220_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='FCM_token',
        ),
        migrations.AddField(
            model_name='appuser',
            name='fcmToken',
            field=models.CharField(blank=True, default='abcdefg', max_length=100, null=True),
        ),
    ]
