# Generated by Django 3.0.14 on 2022-01-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeapp', '0002_auto_20220106_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='name',
            field=models.CharField(default='?', max_length=30),
        ),
    ]
