# Generated by Django 3.0.14 on 2022-01-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placeapp', '0003_label_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='interval_end_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='label',
            old_name='interval_start_time',
            new_name='start_time',
        ),
    ]
