# Generated by Django 3.0.14 on 2022-01-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervalapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interval',
            old_name='pie_chart',
            new_name='daily_path',
        ),
        migrations.AddField(
            model_name='interval',
            name='address',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interval',
            name='emotion',
            field=models.CharField(choices=[('positive', 'Positive'), ('normal', 'Normal'), ('negative', 'Negative')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='interval',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='interval',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
