# Generated by Django 3.0.14 on 2022-01-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervalapp', '0003_interval_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='emotion',
            field=models.CharField(choices=[('positive', 'Positive'), ('normal', 'Normal'), ('negative', 'Negative')], default='normal', max_length=20, null=True),
        ),
    ]
