# Generated by Django 3.0.14 on 2022-01-26 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intervalapp', '0005_auto_20220125_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervalstay',
            name='homelike_latitude',
        ),
        migrations.RemoveField(
            model_name='intervalstay',
            name='homelike_longitude',
        ),
        migrations.RemoveField(
            model_name='intervalstay',
            name='workingplacelike_latitude',
        ),
        migrations.RemoveField(
            model_name='intervalstay',
            name='workingplacelike_longitude',
        ),
    ]
