# Generated by Django 3.0.14 on 2022-02-16 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statisticapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='desc',
            new_name='description',
        ),
        migrations.AddField(
            model_name='weekcategoryinfo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
