# Generated by Django 3.0.14 on 2022-02-16 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statisticapp', '0002_auto_20220216_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='part',
            new_name='sector',
        ),
    ]
