# Generated by Django 3.0.14 on 2022-02-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('textfield', models.TextField()),
            ],
            options={
                'db_table': 'testtable',
            },
        ),
    ]
