# Generated by Django 3.0.14 on 2022-01-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textfield', models.TextField()),
            ],
            options={
                'db_table': 'test',
            },
        ),
    ]
