# Generated by Django 3.0.14 on 2022-02-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textfield', models.TextField()),
            ],
            options={
                'db_table': 'testtable',
            },
        ),
    ]
