# Generated by Django 3.0.14 on 2022-02-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtable',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
