# Generated by Django 3.0.14 on 2022-01-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testtable',
            table='testtable',
        ),
    ]
