# Generated by Django 3.0.14 on 2022-01-14 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dailypathapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(db_column='recommendation_id', primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('pie_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='dailypathapp.DailyPath')),
            ],
            options={
                'db_table': 'recommendation',
            },
        ),
    ]
