# Generated by Django 3.0.14 on 2022-02-16 15:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailypathapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypath',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterModelTable(
            name='dailypath',
            table='dailypath',
        ),
        migrations.CreateModel(
            name='GPSLog',
            fields=[
                ('id', models.BigAutoField(db_column='GPSLog_id', primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('daily_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpslogs', to='dailypathapp.DailyPath')),
            ],
            options={
                'db_table': 'gpslog',
            },
        ),
    ]
