# Generated by Django 3.0.14 on 2022-01-17 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailypathapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypath',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
