# Generated by Django 3.0.14 on 2022-01-18 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailypathapp', '0003_auto_20220118_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpslog',
            name='daily_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpslogs', to='dailypathapp.DailyPath'),
        ),
    ]
